version: '2'

services:
  jekyll-boot:
    build: setup/containers/jekyll-boot/
    image: altus5/jekyll-boot:latest
    container_name: jekyll-boot
    working_dir: /srv/jekyll
    command: /srv/setup/start-jekyll.sh
    ports:
      - "4000:4000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jekyll:/srv/jekyll
      - ./setup:/srv/setup
    volumes_from:
      - datastore

  datastore:
    build: setup/containers/datastore
    image: altus5/jekyll_data:latest
    container_name: datastore

